# Generated by Django 5.1.6 on 2025-02-11 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='classes', to='Authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('HW', 'Homework'), ('TEST', 'Test'), ('EXAM', 'Exam')], max_length=10)),
                ('average_score', models.FloatField()),
                ('general_feedback', models.BooleanField(default=False)),
                ('specific_feedback_count', models.IntegerField(default=0)),
                ('students', models.ManyToManyField(related_name='assignments', to='Authentication.student')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.class')),
            ],
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Exam'), ('TEST', 'Test'), ('HOMEWORK', 'Homework')], max_length=10)),
                ('feedback_file', models.FileField(upload_to='feedback/')),
                ('score', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.student')),
            ],
        ),
    ]
