# Generated by Django 5.1.2 on 2024-10-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='school_name',
        ),
    ]
